### ISSUE TITLE
Support basic keyboard navigation

### ISSUE THREAD

**Issue by mehlium** [KaiOS-Nano-wallet/nano-kaios#4]
Figure out what to do on these keyboard presses:

- [x] ArrowUp  -> Select element before
- [x] ArrowDown -> Select element after
- [x] ArrowLeft -> Go back
- [x] ArrowRight  -> Select nav element, get to supmenu etc.
- [x] Backspace  -> Go back
- [ ] Enter -> Enter middle menu item
- [ ] SoftRight -> Enter right menu item
- [ ] SoftLeft -> Enter soft menu item

**Comment by Citrullin** [comment]
What do you mean with this? I mean, we just need to adapt the solution I had before to svelte. 
Catch the events and call the navigation class on the correct methods. It keeps track of the current selected navigation element etc. 

A summary:
ArrowUp -> Select element before
ArrowDown -> Select element after
ArrowLeft -> Go back
ArrowRight ->  Select nav element, get to supmenu etc.
Backspace -> Go back
Enter -> Enter middle menu item
SoftRight -> Enter right menu item
SoftLeft -> Enter left menu item

**Comment by mehlium** [comment]
Thanks! Didn't know you had them all figured out already :-)

**Comment by Citrullin** [comment]
Comments from #27

"From an UI perspective. I find the previous UI version I had more user friendly. I guess the user doesn't really care about the address. The amount on the wallet is more important. That is why the amount was large before and the name of the wallet small in a separator. We can also put the name at the secondary place. I would definitely place the amount of Nano in focus."

"Also in the menu:
I wouldn't select main from send and receive.
Selecting the wallet after send or receive

Menu -> Send/Receive -> Select wallet -> QR Code/address
I like the small header with the number though. So that the user still sees the context where he currently is. It is a great improvement. Thanks! :)

Generate address doesn't make sense at the frontpage. I think that was my naming right? It should be generate wallet. Or add wallet, or something. ^^

The QR Code can fill most of the screen, no issue with that. Therfore the nano address can get removed. It is, on my phone, even not completely visible. Some of the last characters are not visible.

I really need to fix this scrolling. This is getting very annoying :see_no_evil:  :D"

**Comment by mehlium** [comment]
With a navigation structured figured out and scrolling being fixed in #79 we close this, and open specific issues if we need to.
